fix: update workflow permissions

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -9,6 +9,7 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
         pull-requests: write
+        checks: write
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -22,14 +23,16 @@ jobs:
       - name: Install Poetry
         uses: snok/install-poetry@v1
 
+      - name: Install dependencies
+        run: poetry install
+
       - name: Run unit tests 
         run: |
-          poetry install
           poetry run pytest tests/ --junitxml=report.xml
         
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
-        if: always()   # ensures it runs even if pytest fails
+        if: success() || failure()  # ensures it runs even if pytest fails
         with:
             report_paths: 'report.xml'
             github_token: ${{ secrets.GITHUB_TOKEN }}
